### ISSUE TITLE
用root用户部署集群报错

### ISSUE THREAD

**Issue by fancy-lee** [oceanbase/obdeploy#10]
系统版本：CentOS Linux release 7.9.2009 (Core)
部署三节点，执行obd cluster deploy obtest -c /home/sre/observer.yaml
报错：
Open ssh connection /Exception: Error reading SSH protocol banner[Errno 104] Connection reset by peer
Traceback (most recent call last):
  File "paramiko/transport.py", line 2211, in _check_banner
  File "paramiko/packet.py", line 380, in readline
  File "paramiko/packet.py", line 607, in _read_timeout
ConnectionResetError: [Errno 104] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "paramiko/transport.py", line 2039, in run
  File "paramiko/transport.py", line 2216, in _check_banner
paramiko.ssh_exception.SSHException: Error reading SSH protocol banner[Errno 104] Connection reset by peer

Open ssh connection x
[ERROR] root@172.31.34.75 connect failed: Error reading SSH protocol banner[Errno 104] Connection reset by peer

**Comment by longdafeng** [comment]
It seems something is wrong with your SSH. 

You had better try ssh to target machines by manual. Maybe you can find where is the problem?

You can set user/password in the observer.yaml

**Comment by fancy-lee** [comment]
感谢，已经完美解决，不过希望在安装文档提示一下，需要ssh的访问权限，有些数据库是不用ssh访问的
