### ISSUE TITLE
obd编译成功，执行报错

### ISSUE THREAD

**Issue by ChrisYuan** [oceanbase/obdeploy#113]
编译一切正常，执行obd命令，报错信息如下：

[chris@obdeploy ~]$ obd
Traceback (most recent call last):
  File "obd.py", line 32, in <module>
  File "/usr/lib/python2.7/site-packages/PyInstaller/loader/pyimod03_importers.py", line 391, in load_module
    exec(bytecode, module.__dict__)
  File "core.py", line 32, in <module>
  File "/usr/lib/python2.7/site-packages/PyInstaller/loader/pyimod03_importers.py", line 391, in load_module
    exec(bytecode, module.__dict__)
  File "prettytable.py", line 46, in <module>
  File "/usr/lib/python2.7/site-packages/PyInstaller/loader/pyimod03_importers.py", line 391, in load_module
    exec(bytecode, module.__dict__)
  File "wcwidth/__init__.py", line 12, in <module>
  File "/usr/lib/python2.7/site-packages/PyInstaller/loader/pyimod03_importers.py", line 391, in load_module
    exec(bytecode, module.__dict__)
  File "wcwidth/wcwidth.py", line 79, in <module>
ImportError: No module named functools_lru_cache
[30322] Failed to execute script obd
[chris@obdeploy ~]$

**Comment by frf12** [comment]
请提供下OS版本、Python版本和pyinstaller版本

**Comment by ChrisYuan** [comment]
> 配置信息如下，看是否还需要其他内容信息，我可以再补充：

CentOS Linux release 7.9.2009 (Core)

Python 2.7.5

[chris@obdeploy ~]$ pyinstaller -v
3.6

**Comment by anderson753** [comment]
我也遇到了同样的问题，我是Ubuntu16.04 Python3.8

**Comment by gys-git** [comment]
You can use the latest version of OBD code for compilation. If you still have any issues, please open a new issue to ask your question.
