### ISSUE TITLE
fedora 38 通过obd本地最小化部署失败

### ISSUE THREAD

**Issue by wencan** [oceanbase/obdeploy#173]
OS: Fedora Linux 38 (Workstation Edition) x86_64
Kernel: 6.3.5-200.fc38.x86_64

obd cluster deploy obtest -f -c conf/mini-local-example.yaml：
```
[WARN] Use centos 7 remote mirror repository for fedora 38
+--------------------------------------------------------------------------------------------+
|                                          Packages                                          |
+--------------+---------+------------------------+------------------------------------------+
| Repository   | Version | Release                | Md5                                      |
+--------------+---------+------------------------+------------------------------------------+
| oceanbase-ce | 4.1.0.0 | 101010022023051821.el7 | 21271468e0dee7aaf3d4eff4c4bf5e07421ef6fe |
+--------------+---------+------------------------+------------------------------------------+
Repository integrity check ok
Parameter check ok
Initializes observer work home ok
Remote oceanbase-ce-4.1.0.0-101010022023051821.el7-21271468e0dee7aaf3d4eff4c4bf5e07421ef6fe repository install ok
Remote oceanbase-ce-4.1.0.0-101010022023051821.el7-21271468e0dee7aaf3d4eff4c4bf5e07421ef6fe repository lib check !!
Try to get lib-repository
[WARN] Use centos 7 remote mirror repository for fedora 38
Package oceanbase-ce-libs-4.1.0.0-101010022023051821.el7 is available.
install oceanbase-ce-libs-4.1.0.0 for local ok
Remote oceanbase-ce-libs-4.1.0.0-101010022023051821.el7-d4b3c7985d736b73c7f01eec71b28b984184a48e repository install ok
Remote oceanbase-ce-4.1.0.0-101010022023051821.el7-21271468e0dee7aaf3d4eff4c4bf5e07421ef6fe repository lib check ok
obtest deployed
Trace ID: 6e7d2cde-0906-11ee-b3e8-30d042e5a832
If you want to view detailed obd logs, please run: obd display-trace 6e7d2cde-0906-11ee-b3e8-30d042e5a832
```

obd display-trace 6e7d2cde-0906-11ee-b3e8-30d042e5a832：
```
Traceback (most recent call last):
  File "obd.py", line 1676, in <module>
  File "obd.py", line 1654, in __init__
  File "obd.py", line 1420, in __init__
  File "obd.py", line 1454, in __init__
  File "obd.py", line 1482, in __init__
FileNotFoundError: [Errno 2] No such file or directory
[38013] Failed to execute script 'obd' due to unhandled exception!
```

obd cluster start obtest：
```
Traceback (most recent call last):
  File "obd.py", line 1676, in <module>
  File "obd.py", line 1654, in __init__
  File "obd.py", line 1420, in __init__
  File "obd.py", line 1454, in __init__
  File "obd.py", line 1482, in __init__
FileNotFoundError: [Errno 2] No such file or directory
[38094] Failed to execute script 'obd' due to unhandled exception!
```

**Comment by frf12** [comment]
看记录6e7d2cde-0906-11ee-b3e8-30d042e5a832是deploy命令的日志，但这个命令是成功的。报错的是start命令，能否提供start命令的日志，以及obd --version呢

**Comment by wencan** [comment]
all_in_one的解压目录，和oceanbase的home目录，是同一个目录
force deploy时，部署程序清理了all_in_one目录
可重现

**Comment by wencan** [comment]
obd --version
```
OceanBase Deploy: 2.1.0
REVISION: a44bf47214329b0d9dcbcbed7ab827c0b6d98892
BUILD_BRANCH: HEAD
BUILD_TIME: May 19 2023 10:50:39OURCE
Copyright (C) 2021 OceanBase
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
```

**Comment by wencan** [comment]
@frf12 
我看执行install.sh时，all_in_one的内容已经拷贝到用户主目录下了
执行obd，用的也是主目录下的obd文件
但是部署程序清理的是all_in_one的解压目录，没清理主目录下的all_in_one
按说，不应该file not found

**Comment by frf12** [comment]
@wencan `Traceback (most recent call last):` 上面应该还有日志说明是哪个文件缺失了。可以把提供完整日志吗

**Comment by gys-git** [comment]
Due to the lack of response over an extended period, we will close this issue for now. If you encounter the same issue in a newer version of OBD, you can reopen this issue or create a new one.
