### ISSUE TITLE
obd报错KeyError: 'content-length'

### ISSUE THREAD

**Issue by Listson** [oceanbase/obdeploy#62]
[root@48a7a86a1598 obdeploy]# obd --version
OceanBase Deploy: 1.1.2
REVISION: af5965a19f585217570395b9a4fb08a7ca85d34d
BUILD_BRANCH: master
BUILD_TIME: Nov 03 2021 11:42:34OURCE
Copyright (C) 2021 OceanBase
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
[root@48a7a86a1598 obdeploy]#
[root@48a7a86a1598 obdeploy]#
[root@48a7a86a1598 obdeploy]# obd cluster deploy c1 -c ./example/mini-local-example.yaml -v
- open /root/.obd/version for a+
- cmd: ['c1']
- opts: {'config': './example/mini-local-example.yaml', 'force': False, 'unuselibrepo': None, 'auto_create_tenant': None}
- Get Deploy by name
- mkdir /root/.obd/cluster/
- Get deploy info
- judge deploy status
- config path is None or not
- Create deploy by configuration path
- mkdir /root/.obd/cluster/c1
- copy ./example/mini-local-example.yaml /root/.obd/cluster/c1/config.yaml
- Get deploy configuration
- Search best suitable repository
- Search package for components...
- Get oceanbase-ce repository
- mkdir /root/.obd/repository
- mkdir /root/.obd/repository/oceanbase-ce
- Search oceanbase-ce package from mirror
- mkdir /root/.obd/mirror
- mkdir /root/.obd/mirror/remote
- mkdir /root/.obd/mirror/local
Update OceanBase-community-stable-el7 x
[ERROR] Failed to download http://mirrors.aliyun.com/oceanbase/community/stable/el/7/x86_64///repodata/repomd.xml to /root/.obd/mirror/remote/OceanBase-community-stable-el7/repomd.xml
Traceback (most recent call last):
  File "core.py", line 787, in deploy_cluster
    repositories, install_plugins = self.search_components_from_mirrors_and_install(deploy_config)
  File "core.py", line 660, in search_components_from_mirrors_and_install
    pkgs, repositories, errors = self.search_components_from_mirrors(deploy_config, only_info=False)
  File "core.py", line 215, in search_components_from_mirrors
    pkg = self.mirror_manager.get_best_pkg(name=component, version=config.version, md5=config.package_hash, fuzzy_match=fuzzy_match, only_info=only_info)
  File "_mirror.py", line 789, in get_best_pkg
    return self.get_exact_pkg(**pattern)
  File "_mirror.py", line 778, in get_exact_pkg
    mirrors = self.get_mirrors()
  File "_mirror.py", line 772, in get_mirrors
    mirros = self.get_remote_mirrors()
  File "_mirror.py", line 767, in get_remote_mirrors
    mirror = RemoteMirrorRepository(mirror_path, meta_data, self.stdio)
  File "_mirror.py", line 259, in __init__
    self.update_mirror()
  File "_mirror.py", line 357, in update_mirror
    self.get_repomds(True)
  File "_mirror.py", line 376, in get_repomds
    self.download_file(url, path, self.stdio)
  File "_mirror.py", line 500, in download_file
    file_size = int(fget.headers["Content-Length"])
  File "requests/structures.py", line 54, in __getitem__
KeyError: 'content-length'

[ERROR] Failed to download http://mirrors.aliyun.com/oceanbase/community/stable/el/7/x86_64///repodata/repomd.xml to /root/.obd/mirror/remote/OceanBase-community-stable-el7/repomd.xml
Traceback (most recent call last):
  File "core.py", line 787, in deploy_cluster
    repositories, install_plugins = self.search_components_from_mirrors_and_install(deploy_config)
  File "core.py", line 660, in search_components_from_mirrors_and_install
    pkgs, repositories, errors = self.search_components_from_mirrors(deploy_config, only_info=False)
  File "core.py", line 215, in search_components_from_mirrors
    pkg = self.mirror_manager.get_best_pkg(name=component, version=config.version, md5=config.package_hash, fuzzy_match=fuzzy_match, only_info=only_info)
  File "_mirror.py", line 789, in get_best_pkg
    return self.get_exact_pkg(**pattern)
  File "_mirror.py", line 778, in get_exact_pkg
    mirrors = self.get_mirrors()
  File "_mirror.py", line 772, in get_mirrors
    mirros = self.get_remote_mirrors()
  File "_mirror.py", line 767, in get_remote_mirrors
    mirror = RemoteMirrorRepository(mirror_path, meta_data, self.stdio)
  File "_mirror.py", line 259, in __init__
    self.update_mirror()
  File "_mirror.py", line 358, in update_mirror
    primary_repomd = self._get_repomd_by_type(self.PRIMARY_REPOMD_TYPE)
  File "_mirror.py", line 339, in _get_repomd_by_type
    repodmds = self.get_repomds()
  File "_mirror.py", line 376, in get_repomds
    self.download_file(url, path, self.stdio)
  File "_mirror.py", line 500, in download_file
    file_size = int(fget.headers["Content-Length"])
  File "requests/structures.py", line 54, in __getitem__
KeyError: 'content-length'

Update OceanBase-development-kit-el7 x
[ERROR] Failed to download http://mirrors.aliyun.com/oceanbase/development-kit/el/7/x86_64///repodata/repomd.xml to /root/.obd/mirror/remote/OceanBase-development-kit-el7/repomd.xml
Traceback (most recent call last):
  File "core.py", line 787, in deploy_cluster
    repositories, install_plugins = self.search_components_from_mirrors_and_install(deploy_config)
  File "core.py", line 660, in search_components_from_mirrors_and_install
    pkgs, repositories, errors = self.search_components_from_mirrors(deploy_config, only_info=False)
  File "core.py", line 215, in search_components_from_mirrors
    pkg = self.mirror_manager.get_best_pkg(name=component, version=config.version, md5=config.package_hash, fuzzy_match=fuzzy_match, only_info=only_info)
  File "_mirror.py", line 789, in get_best_pkg
    return self.get_exact_pkg(**pattern)
  File "_mirror.py", line 778, in get_exact_pkg
    mirrors = self.get_mirrors()
  File "_mirror.py", line 772, in get_mirrors
    mirros = self.get_remote_mirrors()
  File "_mirror.py", line 767, in get_remote_mirrors
    mirror = RemoteMirrorRepository(mirror_path, meta_data, self.stdio)
  File "_mirror.py", line 259, in __init__
    self.update_mirror()
  File "_mirror.py", line 357, in update_mirror
    self.get_repomds(True)
  File "_mirror.py", line 376, in get_repomds
    self.download_file(url, path, self.stdio)
  File "_mirror.py", line 500, in download_file
    file_size = int(fget.headers["Content-Length"])
  File "requests/structures.py", line 54, in __getitem__
KeyError: 'content-length'

[ERROR] Failed to download http://mirrors.aliyun.com/oceanbase/development-kit/el/7/x86_64///repodata/repomd.xml to /root/.obd/mirror/remote/OceanBase-development-kit-el7/repomd.xml
Traceback (most recent call last):
  File "core.py", line 787, in deploy_cluster
    repositories, install_plugins = self.search_components_from_mirrors_and_install(deploy_config)
  File "core.py", line 660, in search_components_from_mirrors_and_install
    pkgs, repositories, errors = self.search_components_from_mirrors(deploy_config, only_info=False)
  File "core.py", line 215, in search_components_from_mirrors
    pkg = self.mirror_manager.get_best_pkg(name=component, version=config.version, md5=config.package_hash, fuzzy_match=fuzzy_match, only_info=only_info)
  File "_mirror.py", line 789, in get_best_pkg
    return self.get_exact_pkg(**pattern)
  File "_mirror.py", line 778, in get_exact_pkg
    mirrors = self.get_mirrors()
  File "_mirror.py", line 772, in get_mirrors
    mirros = self.get_remote_mirrors()
  File "_mirror.py", line 767, in get_remote_mirrors
    mirror = RemoteMirrorRepository(mirror_path, meta_data, self.stdio)
  File "_mirror.py", line 259, in __init__
    self.update_mirror()
  File "_mirror.py", line 358, in update_mirror
    primary_repomd = self._get_repomd_by_type(self.PRIMARY_REPOMD_TYPE)
  File "_mirror.py", line 339, in _get_repomd_by_type
    repodmds = self.get_repomds()
  File "_mirror.py", line 376, in get_repomds
    self.download_file(url, path, self.stdio)
  File "_mirror.py", line 500, in download_file
    file_size = int(fget.headers["Content-Length"])
  File "requests/structures.py", line 54, in __getitem__
KeyError: 'content-length'

Traceback (most recent call last):
  File "core.py", line 787, in deploy_cluster
    repositories, install_plugins = self.search_components_from_mirrors_and_install(deploy_config)
  File "core.py", line 660, in search_components_from_mirrors_and_install
    pkgs, repositories, errors = self.search_components_from_mirrors(deploy_config, only_info=False)
  File "core.py", line 215, in search_components_from_mirrors
    pkg = self.mirror_manager.get_best_pkg(name=component, version=config.version, md5=config.package_hash, fuzzy_match=fuzzy_match, only_info=only_info)
  File "_mirror.py", line 789, in get_best_pkg
    return self.get_exact_pkg(**pattern)
  File "_mirror.py", line 778, in get_exact_pkg
    mirrors = self.get_mirrors()
  File "_mirror.py", line 773, in get_mirrors
    mirros.append(self.local_mirror)
  File "_mirror.py", line 725, in local_mirror
    self._local_mirror = LocalMirrorRepository(self.local_path, self.stdio)
  File "_mirror.py", line 541, in __init__
    self._load_db()
  File "_mirror.py", line 549, in _load_db
    with open(self.db_path, 'rb') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/root/.obd/mirror/local/.db'

- md5 is None
- name is oceanbase-ce
- arch is ['ia32e', 'x86_64', 'athlon', 'i686', 'i586', 'i486', 'i386', 'noarch']
- release is None
- version is None
[ERROR] Failed to download http://mirrors.aliyun.com/oceanbase/community/stable/el/7/x86_64///repodata/repomd.xml to /root/.obd/mirror/remote/OceanBase-community-stable-el7/repomd.xml
Traceback (most recent call last):
  File "core.py", line 787, in deploy_cluster
    repositories, install_plugins = self.search_components_from_mirrors_and_install(deploy_config)
  File "core.py", line 660, in search_components_from_mirrors_and_install
    pkgs, repositories, errors = self.search_components_from_mirrors(deploy_config, only_info=False)
  File "core.py", line 215, in search_components_from_mirrors
    pkg = self.mirror_manager.get_best_pkg(name=component, version=config.version, md5=config.package_hash, fuzzy_match=fuzzy_match, only_info=only_info)
  File "_mirror.py", line 789, in get_best_pkg
    return self.get_exact_pkg(**pattern)
  File "_mirror.py", line 781, in get_exact_pkg
    new_one = mirror.get_exact_pkg_info(**pattern)
  File "_mirror.py", line 433, in get_exact_pkg_info
    for key in self.db:
  File "_mirror.py", line 265, in db
    primary_repomd = self._get_repomd_by_type(self.PRIMARY_REPOMD_TYPE)
  File "_mirror.py", line 339, in _get_repomd_by_type
    repodmds = self.get_repomds()
  File "_mirror.py", line 376, in get_repomds
    self.download_file(url, path, self.stdio)
  File "_mirror.py", line 500, in download_file
    file_size = int(fget.headers["Content-Length"])
  File "requests/structures.py", line 54, in __getitem__
KeyError: 'content-length'

- MirrorRepositoryType.REMOTE mirror OceanBase-community-stable-el7 found pkg: None
- md5 is None
- name is oceanbase-ce
- arch is ['ia32e', 'x86_64', 'athlon', 'i686', 'i586', 'i486', 'i386', 'noarch']
- release is None
- version is None
[ERROR] Failed to download http://mirrors.aliyun.com/oceanbase/development-kit/el/7/x86_64///repodata/repomd.xml to /root/.obd/mirror/remote/OceanBase-development-kit-el7/repomd.xml
Traceback (most recent call last):
  File "core.py", line 787, in deploy_cluster
    repositories, install_plugins = self.search_components_from_mirrors_and_install(deploy_config)
  File "core.py", line 660, in search_components_from_mirrors_and_install
    pkgs, repositories, errors = self.search_components_from_mirrors(deploy_config, only_info=False)
  File "core.py", line 215, in search_components_from_mirrors
    pkg = self.mirror_manager.get_best_pkg(name=component, version=config.version, md5=config.package_hash, fuzzy_match=fuzzy_match, only_info=only_info)
  File "_mirror.py", line 789, in get_best_pkg
    return self.get_exact_pkg(**pattern)
  File "_mirror.py", line 781, in get_exact_pkg
    new_one = mirror.get_exact_pkg_info(**pattern)
  File "_mirror.py", line 433, in get_exact_pkg_info
    for key in self.db:
  File "_mirror.py", line 265, in db
    primary_repomd = self._get_repomd_by_type(self.PRIMARY_REPOMD_TYPE)
  File "_mirror.py", line 339, in _get_repomd_by_type
    repodmds = self.get_repomds()
  File "_mirror.py", line 376, in get_repomds
    self.download_file(url, path, self.stdio)
  File "_mirror.py", line 500, in download_file
    file_size = int(fget.headers["Content-Length"])
  File "requests/structures.py", line 54, in __getitem__
KeyError: 'content-length'

- MirrorRepositoryType.REMOTE mirror OceanBase-development-kit-el7 found pkg: None
- md5 is None
- name is oceanbase-ce
- arch is ['ia32e', 'x86_64', 'athlon', 'i686', 'i586', 'i486', 'i386', 'noarch']
- release is None
- version is None
- MirrorRepositoryType.LOCAL mirror local found pkg: None
[ERROR] No such package oceanbase-ce.

**Comment by frf12** [comment]
请检查机器能否ping通 mirrors.aliyun.com/oceanbase。如果不能请删除~/.obd/mirror/remote/OceanBase.repo，后使用离线部署的方案https://open.oceanbase.com/docs/community/oceanbase-database/V3.1.1/install-the-oceanbase-database-by-using-the-rpm-package

**Comment by frf12** [comment]
可以将OBD升级到1.2.0以上。使用`obd mirror disable remote`关闭远程仓库
